version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15
        environment:
            NODE_ENV: development
        working_directory: ~/repo
        steps:
        
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

            - run: npm install

            - run: npm install mocha-junit-reporter # just for CircleCI

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package-lock.json" }}

            - run: mkdir reports

            # Run mocha
            - run:
                name: npm test
                command: npm run test:ci
                when: always

            # Run coverage report for Code Climate
            - run:
                name: code-coverage
                command: npm run report

            # Upload results

            - store_test_results:
                path: reports

            - store_artifacts:
                path: ./reports/test-results.xml

            - store_artifacts: # upload test coverage as artifact
                path: ./coverage/lcov.info
                prefix: tests
